### ISSUE TITLE
ltx i2v trainer

### ISSUE THREAD

**Issue by YLongJin** [a-r-r-o-w/finetrainers#138]
how to train ltx lora image to video？

**Comment by a-r-r-o-w** [comment]
I've added some initial support for this in #150. Still not 100% sure that it works, but I'm running some experiments to verify it soon. Feel free to give it a try and let us know if anything doesn't work as expected

**Comment by YLongJin** [comment]
@a-r-r-o-w  cool I will try it

**Comment by YLongJin** [comment]
I got this bug:

ERROR:finetrainers:An error occurred during training: Training type lora_i2v not supported for model ltx_video. Supported training types are: ['lora']
ERROR:finetrainers:Traceback (most recent call last):
  File "/mnt/finetrainers/train.py", line 26, in main
    trainer = Trainer(args)
  File "/mnt/finetrainers/finetrainers/trainer.py", line 91, in __init__
    self.model_config = get_config_from_model_name(self.args.model_name, self.args.training_type)
  File "/mnt/finetrainers/finetrainers/models.py", line 23, in get_config_from_model_name
    raise ValueError(
ValueError: Training type lora_i2v not supported for model ltx_video. Supported training types are: ['lora']

**Comment by sayakpaul** [comment]
What is your training command?

**Comment by YLongJin** [comment]
@sayakpaul  Now I checkout to i2v branch， it is work，but I think the lora is not work，the generate video is same as no lora

**Comment by sayakpaul** [comment]
I am not sure I understand. Could you please elaborate a bit?

**Comment by YLongJin** [comment]
#!/bin/bash

# export TORCH_LOGS="+dynamo,recompiles,graph_breaks"
# export TORCHDYNAMO_VERBOSE=1
export WANDB_MODE="offline"
export NCCL_P2P_DISABLE=1
export TORCH_NCCL_ENABLE_MONITORING=0

GPU_IDS="2,3"

DATA_ROOT="/mnt/CogVLM2/clear_video"
CAPTION_COLUMN="direct_prompt_wash.txt "
VIDEO_COLUMN="videos_wash.txt"

ID_TOKEN="cccc"
# ID_TOKEN=""
# Model arguments
model_cmd="--model_name ltx_video \
  --pretrained_model_name_or_path /mnt/finetrainers/LTX-Video"


# Dataset arguments
dataset_cmd="--data_root $DATA_ROOT \
  --video_column $VIDEO_COLUMN \
  --caption_column $CAPTION_COLUMN \
  --id_token $ID_TOKEN \
  --video_resolution_buckets 193x512x1152 193x768x768 193x1024x576 193x1280x460 193x1536x384 97x512x1152 97x768x768 97x1024x576 97x1280x460 97x1536x384 \
  --precompute_conditions"

# Dataloader arguments
dataloader_cmd="--dataloader_num_workers 0"

# Diffusion arguments
diffusion_cmd="--flow_resolution_shifting"

# Training arguments
training_cmd="--training_type lora_i2v \
  --seed 42 \
  --mixed_precision bf16 \
  --batch_size 1 \
  --train_steps 10000 \
  --target_modules to_q to_k to_v to_out.0 \
  --gradient_accumulation_steps 1 \
  --gradient_checkpointing \
  --checkpointing_steps 2000 \
  --checkpointing_limit 2 \
  --enable_slicing \
  --enable_tiling"

# Optimizer arguments
optimizer_cmd="--optimizer adamw \
  --lr 1e-4 \
  --lr_scheduler cosine_with_restarts \
  --lr_warmup_steps 100 \
  --lr_num_cycles 1 \
  --beta1 0.9 \
  --beta2 0.95 \
  --weight_decay 1e-4 \
  --epsilon 1e-8 \
  --max_grad_norm 1.0"

# Validation arguments
validation_cmd="--validation_prompts \"$ID_TOKEN left to right A wooden deck extends across the foreground, featuring horizontal planks of light grayish-brown wood.  A wooden railing with vertical supports runs along the edge of the deck.  Beyond the railing, a grassy yard stretches to a dense line of green trees.  A light taupe-colored house with a sloped roof is visible in the background, partially bordering the deck area. A small portion of a shed-like structure is also visible in the background of the yard. The lighting suggests an outdoor daytime setting. The perspective is from a point slightly above the deck level, looking out over the yard and trees. The composition is straightforward and realistic, focused on the view from the deck. The colors are natural, with various shades of green, light brown, and taupe. The overall atmosphere is calm and serene, evocative of a residential backyard setting.@@@49x768x768:::$ID_TOKEN right to left A light-filled kitchen, featuring wooden cabinets in a mix of red-brown and creamy beige tones.  The cabinets are arranged around a central island with a light beige countertop. The floors are a light hardwood.  Two tall, cream-colored pantry closets are positioned on the left side of the image, taking up a significant portion of the left wall space.  The kitchen's walls include a floral wallpaper pattern.  A white refrigerator and dishwasher are visible, along with recessed lighting fixtures.  Three pendant lights hang over a kitchen counter with a stainless steel sink.  A window with light-colored window coverings is visible, showcasing a view outdoors. The overall impression is of a spacious, traditional kitchen with a warm and inviting atmosphere. The light predominantly comes from the windows, casting a natural illumination throughout the room. The perspective is at a level that encompasses the entire kitchen interior.  The composition is balanced, with the closets in the foreground drawing the viewer's eye toward the center of the room.@@@87x768x512\" \
  --validation_images \"$DATA_ROOT/images/00a861d699fb7797_part3.png:::$DATA_ROOT/images/00a87dd567cdc292_part1.png\" \
  --num_validation_videos 1 \
  --validation_steps 2000"


# REGULARIZATION_CMDS=("--caption_dropout_p 0.00" "--caption_dropout_p 0.05" "--caption_dropout_p 0.05 --image_condition_dropout_p 0.05 --image_condition_noise_scale 0.00" "--caption_dropout_p 0.05 --image_condition_dropout_p 0.05 --image_condition_noise_scale 0.1" "--caption_dropout_p 0.05 --image_condition_dropout_p 0.1 --image_condition_noise_scale 0.1")
REGULARIZATION_CMDS=("--caption_dropout_p 0.05")

LORA_CONFIGS=("--rank 256 --lora_alpha 256")

for regularization_cmd in "${REGULARIZATION_CMDS[@]}"
do
  sanitized_regularization_cmd=$(echo "$regularization_cmd" | sed 's/--//g; s/ /_/g; s/=/-/g')
  
  miscellaneous_cmd="--tracker_name finetrainers-ltxv \
    --output_dir ./resolution—ltx-video-$sanitized_regularization_cmd \
    --nccl_timeout 1800 \
    --report_to wandb"
  
  cmd="accelerate launch --config_file accelerate_configs/uncompiled_2.yaml --gpu_ids $GPU_IDS train.py \
    $model_cmd \
    $dataset_cmd \
    $dataloader_cmd \
    $diffusion_cmd \
    $training_cmd --rank 128 --lora_alpha 128 \
    $optimizer_cmd \
    $validation_cmd \
    $regularization_cmd \
    $lora_config \
    $miscellaneous_cmd"

  echo "Running command: $cmd"
  eval $cmd
  echo -ne "-------------------- Finished executing script --------------------\n\n"
done

for lora_config in "${LORA_CONFIGS[@]}"
do
  sanitized_lora_config=$(echo "$lora_config" | sed 's/--//g; s/ /_/g; s/=/-/g')
  regularization_cmd="--caption_dropout_p 0.05"
  
  miscellaneous_cmd="--tracker_name finetrainers-ltxv \
    --output_dir /raid/aryan/ltx-video-$sanitized_lora_config \
    --nccl_timeout 1800 \
    --report_to wandb"
  
  cmd="accelerate launch --config_file accelerate_configs/uncompiled_2.yaml --gpu_ids $GPU_IDS train.py \
    $model_cmd \
    $dataset_cmd \
    $dataloader_cmd \
    $diffusion_cmd \
    $training_cmd \
    $optimizer_cmd \
    $validation_cmd \
    $regularization_cmd \
    $lora_config \
    $miscellaneous_cmd"

  echo "Running command: $cmd"
  eval $cmd
  echo -ne "-------------------- Finished executing script --------------------\n\n"
done

**Comment by sayakpaul** [comment]
I2V trainer is still being worked on the PR: #187. Please use that PR to report these.
