### ISSUE TITLE
Help me with custom dataset

### ISSUE THREAD

**Issue by saikanov** [a-r-r-o-w/finetrainers#146]
### System Info / 系統信息

Hey a-r-r-o-w, thanks for your great work, please help me with this problem.

So i make custom dataset, this is just test dataset so i use 5 video but i got this error when running dataset_preparation.sh

===== Running `  torchrun --nproc_per_node=1     cogvideox/prepare_dataset.py       --model_id THUDM/CogVideoX-2b       --data_root /workspace/cogvideox-factory/dataset-mini       --caption_column prompt.txt       --video_column videos.txt       --output_dir /workspace/cogvideox-factory/preprocessed-dataset-mini       --height_buckets 480 720       --width_buckets 720 960       --frame_buckets 49       --max_num_frames 49       --max_sequence_length 226       --target_fps 8       --batch_size 1       --dtype fp32
 --save_latents_and_embeddings` =====
Downloading shards: 100%|███████████████████████| 2/2 [00:00<00:00, 1666.06it/s]
Loading checkpoint shards: 100%|██████████████████| 2/2 [00:12<00:00,  6.37s/it]
Encoding: 100%|███████████████████████████████████| 5/5 [00:56<00:00, 11.29s/it]
Completed preprocessing latents and embeddings. Temporary files from all ranks saved to `/workspace/cogvideox-factory/preprocessed-dataset-mini/tmp`
[rank0]: Traceback (most recent call last):
[rank0]:   File "/workspace/cogvideox-factory/training/cogvideox/prepare_dataset.py", line 669, in <module>
[rank0]:     main()
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/workspace/cogvideox-factory/training/cogvideox/prepare_dataset.py", line 651, in main
[rank0]:     with open(video_metadata_txt, "r", encoding="utf-8") as metadata_file:
[rank0]: FileNotFoundError: [Errno 2] No such file or directory: '/workspace/cogvideox-factory/preprocessed-dataset-mini/videos/2a2d7fcb-0c68-46b4-9576-aea4c06e2fc6.txt'
E1225 10:33:11.263000 140693641503872 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 37957) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
cogvideox/prepare_dataset.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-12-25_10:33:11
  host      : aa04a3d47c81
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 37957)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
===== Finished running script =====
CPU times: user 2.15 s, sys: 330 ms, total: 2.48 s
Wall time: 1min 26s

![Screenshot 2024-12-25 174041](https://github.com/user-attachments/assets/cc87957a-a480-4780-bcc4-34cb9adfe44b)
![Screenshot 2024-12-25 174018](https://github.com/user-attachments/assets/0ea66458-6f0f-4dae-9788-431fcf02d632)
![Screenshot 2024-12-25 174009](https://github.com/user-attachments/assets/5c7bddbe-54a1-408e-ab6f-d3f8309e4664)
![Screenshot 2024-12-25 184622](https://github.com/user-attachments/assets/7e848b9a-e04f-462e-9b6e-1523a475137a)

i think i already setting this right. what is the problem could be?

i successfully doing this with disney-dataset, so i think the problem is on my dataset format.

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

https://huggingface.co/datasets/saikanov/test-cogvideo/resolve/main/dataset-mini.rar

i upload the dataset i use on hf if you want to reproduce the case

and this is the .sh 

#!/bin/bash

MODEL_ID="THUDM/CogVideoX-2b"

NUM_GPUS=1

# For more details on the expected data format, please refer to the README.
DATA_ROOT="/workspace/cogvideox-factory/dataset-mini"  # This needs to be the path to the base directory where your videos are located.
CAPTION_COLUMN="prompt.txt"
VIDEO_COLUMN="videos.txt"
OUTPUT_DIR="/workspace/cogvideox-factory/preprocessed-dataset-mini"
HEIGHT_BUCKETS="480 720"
WIDTH_BUCKETS="720 960"
FRAME_BUCKETS="49"
MAX_NUM_FRAMES="49"
MAX_SEQUENCE_LENGTH=226
TARGET_FPS=8
BATCH_SIZE=1
DTYPE=fp32

# To create a folder-style dataset structure without pre-encoding videos and captions
# For Image-to-Video finetuning, make sure to pass `--save_image_latents`
CMD_WITHOUT_PRE_ENCODING="\
  torchrun --nproc_per_node=$NUM_GPUS \
    cogvideox/prepare_dataset.py \
      --model_id $MODEL_ID \
      --data_root $DATA_ROOT \
      --caption_column $CAPTION_COLUMN \
      --video_column $VIDEO_COLUMN \
      --output_dir $OUTPUT_DIR \
      --height_buckets $HEIGHT_BUCKETS \
      --width_buckets $WIDTH_BUCKETS \
      --frame_buckets $FRAME_BUCKETS \
      --max_num_frames $MAX_NUM_FRAMES \
      --max_sequence_length $MAX_SEQUENCE_LENGTH \
      --target_fps $TARGET_FPS \
      --batch_size $BATCH_SIZE \
      --dtype $DTYPE
"

CMD_WITH_PRE_ENCODING="$CMD_WITHOUT_PRE_ENCODING --save_latents_and_embeddings"

# Select which you'd like to run
CMD=$CMD_WITH_PRE_ENCODING

echo "===== Running \`$CMD\` ====="
eval $CMD
echo -ne "===== Finished running script =====\n"

### Expected behavior / 期待表现

i want to make it run like the disney-dataset

**Comment by sayakpaul** [comment]
The contents of the [disney dataset](https://huggingface.co/datasets/Wild-Heart/Disney-VideoGeneration-Dataset) are as follows:

```bash
LICENSE  prompt.txt  README.md  README_zh.md  videos  videos.txt
```

Contents of the `videos.txt` file:

```bash
videos/a3c275fc2eb0a67168a7c58a6a9adb14.mp4
videos/8ae679ab483ab344c881d4a813e0cb51.mp4
videos/6619a387964ad49eb1127079d25d17d8.mp4
videos/bf06573576ae0ea4d27a178b4d6e95a1.mp4
videos/907704ed979d5e5651fac98ccbec2d4b.mp4
videos/96d342ea7c7cfddbe1106072bc34be5a.mp4
videos/328fc12cf9cf3d540e67efadeb893f61.mp4
videos/4adbb3a2945c9edd78785daccfd23e80.mp4
videos/1151c01bd77450dfc603a2eb7352822e.mp4
videos/81c5dab878d73e6c21181d18d83f2808.mp4
...
```

`prompt.txt` is simple the prompts belonging to the videos in an ordered manner. 

So, I think your dataset has the right structure. I would suggest investigating the contents of the metadata here in this line: `with open(video_metadata_txt, "r", encoding="utf-8") as metadata_file:` (as this is the line that causes the errors).

**Comment by saikanov** [comment]
[](https://github.com/a-r-r-o-w/finetrainers/issues/146#issuecomment-2564974630)

@sayakpaul hey, i got time to do this again.

the problem is some video doesnt have metadata 

what could be wrong with the dataset? arent it just need to be splitted to 6sec/video? does i need to do some other refine to the dataset?
